namespace: wackopicko
output:
  file_path: ./Fluid-Attacks-Sast-Results.csv
  format: CSV

working_dir: .
language: EN

sast:
  include:
    - .
  exclude:
    - glob(**/node_modules/**)
    - glob(**/vendor/**)
    - glob(**/dist/**)
